package com.codeferm.periphery.device;

import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.lang.foreign.ValueLayout;
import java.util.HashMap;
import java.util.Map;
import lombok.extern.slf4j.Slf4j;
import org.periphery.Periphery;
import org.periphery.i2c_msg;

/**
 * ADXL345 3-Axis digital accelerometer device class.
 * <p>
 * This class provides a high-level interface to the ADXL345 accelerometer using direct FFM bindings to c-periphery. It utilizes
 * hardware-accurate i2c_msg structures generated by jextract to ensure cross-architecture compatibility (ARM64/x86_64).
 * </p>
 *
 * @author Steven P. Goldsmith
 * @version 1.0.0-SNAPSHOT
 * @since 1.0.0
 */
@Slf4j
public class Adxl345 implements AutoCloseable {

    /**
     * Native i2c_handle MemorySegment.
     */
    private final MemorySegment handle;

    /**
     * I2C address of the ADXL345 device.
     */
    private final short address;

    /**
     * Scaling factor used to convert raw register values to G-force.
     */
    private float scalingFactor;

    /**
     * Shared arena for the lifecycle of the device and its native buffers.
     */
    private final Arena arena;

    /**
     * Size of the i2c_msg structure as determined by the native bindings.
     */
    private static final long MSG_SIZE = i2c_msg.layout().byteSize();

    /**
     * Persistent buffer for i2c_msg structures.
     */
    private final MemorySegment msgBuffer;

    /**
     * Reusable native buffer for I2C data payload.
     */
    private final MemorySegment dataBuffer;

    /**
     * Earth gravity constant in m/s^2.
     */
    private static final float G_TO_MS2 = 9.80665f;

    /**
     * I2C Read flag (I2C_M_RD).
     */
    private static final short I2C_M_RD = 0x0001;

    /**
     * Initialize ADXL345 with a native I2C handle and device address.
     *
     * @param arena Arena to manage the handle and buffer lifetime.
     * @param handle MemorySegment allocated using the precision i2c_handle layout.
     * @param address I2C address of the ADXL345.
     */
    public Adxl345(final Arena arena, final MemorySegment handle, final short address) {
        this.arena = arena;
        this.handle = handle;
        this.address = address;
        // Allocate space for 2 messages using the native structure size
        this.msgBuffer = arena.allocate(MSG_SIZE * 2);
        // Pre-allocate data buffer for max transaction size (1 reg + 6 axes)
        this.dataBuffer = arena.allocate(7);
        log.atDebug().log("ADXL345 driver initialized for 0x{}", Integer.toHexString(address));
    }

    /**
     * Helper to set i2c_msg fields using hardware-accurate jextract setters.
     *
     * @param msgIdx Index of the message in the buffer (0 or 1).
     * @param addr I2C slave address.
     * @param flags Operation flags (0 for write, I2C_M_RD for read).
     * @param buf MemorySegment pointing to the data.
     * @param len Length of the data to transfer.
     */
    private void setMsg(final int msgIdx, final short addr, final short flags,
            final MemorySegment buf, final int len) {
        final var msg = msgBuffer.asSlice(msgIdx * MSG_SIZE, MSG_SIZE);
        i2c_msg.addr(msg, addr);
        i2c_msg.flags(msg, flags);
        i2c_msg.len(msg, (short) len);
        i2c_msg.buf(msg, buf);
    }

    /**
     * Writes an 8-bit value to a device register.
     *
     * @param reg Register address.
     * @param value Value to write.
     */
    public void writeReg8(final short reg, final short value) {
        dataBuffer.set(ValueLayout.JAVA_BYTE, 0, (byte) reg);
        dataBuffer.set(ValueLayout.JAVA_BYTE, 1, (byte) value);
        setMsg(0, address, (short) 0, dataBuffer, 2);
        if (Periphery.i2c_transfer(handle, msgBuffer, 1) < 0) {
            log.error("I2C write failed for register 0x{}", Integer.toHexString(reg));
        }
    }

    /**
     * Reads an 8-bit value from a device register.
     *
     * @param reg Register address.
     * @return The 8-bit value read.
     */
    public short readReg8(final short reg) {
        dataBuffer.set(ValueLayout.JAVA_BYTE, 0, (byte) reg);
        setMsg(0, address, (short) 0, dataBuffer, 1);
        setMsg(1, address, I2C_M_RD, dataBuffer.asSlice(1, 1), 1);
        if (Periphery.i2c_transfer(handle, msgBuffer, 2) < 0) {
            log.error("I2C read failed for register 0x{}", Integer.toHexString(reg));
        }
        return (short) (dataBuffer.get(ValueLayout.JAVA_BYTE, 1) & 0xff);
    }

    /**
     * Enable the device and set default configuration.
     */
    public void enable() {
        writeReg8((short) 0x2d, (short) 0x08); // POWER_CTL: Measure
        setRange((short) 0x00);                // +/- 2g
        setDataRate((short) 0x0a);             // 100 Hz
        refreshScalingFactor();
    }

    /**
     * Sets the measurement range in the DATA_FORMAT register.
     *
     * @param value Range value.
     */
    public void setRange(final short value) {
        final var current = readReg8((short) 0x31);
        final var newValue = (short) (((current & ~0x0f) | value) | 0x08);
        writeReg8((short) 0x31, newValue);
        refreshScalingFactor();
    }

    /**
     * Sets the data rate in the BW_RATE register.
     *
     * @param value Rate value.
     */
    public void setDataRate(final short value) {
        writeReg8((short) 0x2c, (short) (value & 0x0f));
    }

    /**
     * Updates internal scaling factor based on current resolution settings.
     */
    public void refreshScalingFactor() {
        final var format = readReg8((short) 0x31);
        if ((format & 0x08) == 0x08) {
            this.scalingFactor = 0.004f;
        } else {
            final var range = (short) (format & 0x03);
            final var gRange = 4.0f * (float) Math.pow(2, range);
            this.scalingFactor = gRange / 1024.0f;
        }
    }

    /**
     * Reads x, y, z axes and returns scaled acceleration in m/s^2.
     *
     * @return Map containing "x", "y", and "z" float values.
     */
    public Map<String, Float> read() {
        dataBuffer.set(ValueLayout.JAVA_BYTE, 0, (byte) 0x32); // DATAX0
        setMsg(0, address, (short) 0, dataBuffer, 1);
        setMsg(1, address, I2C_M_RD, dataBuffer.asSlice(1, 6), 6);

        if (Periphery.i2c_transfer(handle, msgBuffer, 2) < 0) {
            log.error("I2C read axes failed");
        }

        final var x = (short) (((dataBuffer.get(ValueLayout.JAVA_BYTE, 2) & 0xff) << 8)
                | (dataBuffer.get(ValueLayout.JAVA_BYTE, 1) & 0xff));
        final var y = (short) (((dataBuffer.get(ValueLayout.JAVA_BYTE, 4) & 0xff) << 8)
                | (dataBuffer.get(ValueLayout.JAVA_BYTE, 3) & 0xff));
        final var z = (short) (((dataBuffer.get(ValueLayout.JAVA_BYTE, 6) & 0xff) << 8)
                | (dataBuffer.get(ValueLayout.JAVA_BYTE, 5) & 0xff));

        final var map = new HashMap<String, Float>();
        map.put("x", x * scalingFactor * G_TO_MS2);
        map.put("y", y * scalingFactor * G_TO_MS2);
        map.put("z", z * scalingFactor * G_TO_MS2);
        return map;
    }

    /**
     * Reads the device ID from the DEVID register.
     *
     * @return The device ID (0xE5).
     */
    public short getDeviceId() {
        return readReg8((short) 0x00);
    }

    /**
     * Closes the ADXL345 and releases the native I2C handle.
     */
    @Override
    public void close() {
        if (handle != null && handle.address() != 0) {
            Periphery.i2c_close(handle);
        }
    }
}
