<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.codeferm</groupId>
        <artifactId>javauio2</artifactId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>

    <groupId>com.codeferm</groupId>
    <artifactId>demo2</artifactId>
    <version>1.0.0-SNAPSHOT</version>    

    <name>Demo 2</name>
    <description>Java UIO 2 Demos</description>

    <profiles>
        <profile>
            <id>x86_64</id>
            <activation>
                <activeByDefault>true</activeByDefault>
            </activation>
            <properties>
                <native.arch>x86_64</native.arch>
            </properties>
        </profile>
        <profile>
            <id>arm32</id>
            <properties>
                <native.arch>arm32</native.arch>
            </properties>
        </profile>
        <profile>
            <id>arm64</id>
            <properties>
                <native.arch>arm64</native.arch>
            </properties>
        </profile>
    </profiles>     
                                             
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <fork>true</fork>
                    <annotationProcessorPaths>
                        <path>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                            <version>${lombok.version}</version>
                        </path>
                        <path>
                            <groupId>info.picocli</groupId>
                            <artifactId>picocli-codegen</artifactId>
                            <version>${picocli.version}</version>
                        </path>      
                    </annotationProcessorPaths>
                    <compilerArgs>
                        <arg>-J--sun-misc-unsafe-memory-access=allow</arg>
                    </compilerArgs>    
                </configuration>
            </plugin>
            
            <plugin>
                <artifactId>maven-assembly-plugin</artifactId>
                <version>3.7.1</version>
                <configuration>
                    <descriptorRefs>
                        <descriptorRef>jar-with-dependencies</descriptorRef>
                    </descriptorRefs>
                </configuration>
                <executions>
                    <execution>
                        <id>make-assembly</id>
                        <phase>package</phase>
                        <goals>
                            <goal>single</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>                                    
        </plugins>
    </build>

    <dependencies>
        <!-- Compile -->
        <dependency>
            <groupId>com.codeferm</groupId>
            <artifactId>periphery2</artifactId>
            <version>1.0.0-SNAPSHOT</version>   
        </dependency>   
        <dependency>
            <groupId>com.codeferm</groupId>
            <artifactId>u8g22</artifactId>
            <version>1.0.0-SNAPSHOT</version>   
        </dependency>        
        <dependency>
            <groupId>info.picocli</groupId>
            <artifactId>picocli</artifactId>
        </dependency>   
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
        </dependency>
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
        </dependency>
        <!-- Provided -->
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <scope>provided</scope>
        </dependency>
    </dependencies>
</project>